version: "3.1"

services:
  db:
    image: docker.io/postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: default
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data:rw
